services:
  - type: web
    name: cotisations-app
    env: docker
    region: frankfurt
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cotisations-db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: SESSION_DRIVER
        value: cookie

databases:
  - name: cotisations-db
    region: frankfurt
    plan: free
    databaseName: cotisations
    user: cotisations_user
