services:
  - type: web
    name: cotisations-app
    env: php
    region: frankfurt
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader && npm install && npm run build && php artisan config:cache && php artisan route:cache && php artisan view:cache
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_ENV
        value: production
      - key: APP_URL
        fromService:
          type: web
          name: cotisations-app
          property: url
      - key: DATABASE_URL
        fromDatabase:
          name: cotisations-db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: SESSION_DRIVER
        value: cookie

databases:
  - name: cotisations-db
    region: frankfurt
    plan: free
    databaseName: cotisations
    user: cotisations_user
