services:
  - type: web
    name: cotisations-app
    env: docker
    region: frankfurt
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_ENV
        value: production
      - key: APP_URL
        fromService:
          type: web
          name: cotisations-app
          property: host
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: cotisations-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cotisations-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: cotisations-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: cotisations-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cotisations-db
          property: password
      - key: SESSION_DRIVER
        value: cookie

databases:
  - name: cotisations-db
    region: frankfurt
    plan: free
    databaseName: cotisations
    user: cotisations_user
